"""Generate ``papers/index.json`` and the Markdown paper lists from the config.

``configs/papers.yaml`` is the single source of truth. Everything else that lists
a paper is generated from it by this script, because the alternative -- five
hand-maintained stores -- is what let two cited papers go unregistered in the
first place.

Run after editing the config::

    python scripts/generate_paper_index.py

``tests/test_paper_citations.py`` fails if the generated files fall out of sync,
so a forgotten run is caught rather than merged.
"""

from __future__ import annotations

import json
from pathlib import Path

from qprac_lab.config import PROJECT_ROOT, load_config
from qprac_lab.papers.registry import SECTIONS, markdown_citation, resolve

SECTION_TITLES = {
    "simulation": "Simulation",
    "optimization": "Optimization",
    "pdes": "PDEs",
    "qml": "Quantum Machine Learning",
}

TUTORIAL_DIRS = {
    "simulation": "01-simulation",
    "optimization": "02-optimization",
    "pdes": "03-pdes",
    "qml": "04-qml",
}

BANNER = "<!-- Generated by scripts/generate_paper_index.py from configs/papers.yaml. -->"


def _papers() -> dict[str, list[dict]]:
    return load_config("papers")["papers"]


def write_index() -> Path:
    """The machine-readable index, with every field needed to resolve a paper."""
    payload = {
        section: [
            {
                key: entry[key]
                for key in ("title", "authors", "year", "topic", "venue", "doi", "arxiv", "url")
                if key in entry
            }
            | {"resolves_to": resolve(entry)}
            for entry in entries
        ]
        for section, entries in _papers().items()
    }
    path = PROJECT_ROOT / "papers" / "index.json"
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return path


def write_section_markdown() -> list[Path]:
    """``papers/<section>.md`` -- the prose library, grouped by topic."""
    written = []
    for section, entries in _papers().items():
        lines = [BANNER, "", f"# {SECTION_TITLES.get(section, section.title())} Papers", ""]
        by_topic: dict[str, list[dict]] = {}
        for entry in entries:
            by_topic.setdefault(entry.get("topic", "Other"), []).append(entry)
        for topic, group in by_topic.items():
            lines.append(f"## {topic}")
            lines.append("")
            lines.extend(markdown_citation(entry) for entry in group)
            lines.append("")
        path = PROJECT_ROOT / "papers" / f"{section}.md"
        path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
        written.append(path)
    return written


def write_tutorial_markdown() -> list[Path]:
    """``tutorials/<dir>/papers.md`` -- the per-section reference list."""
    written = []
    for section, directory in TUTORIAL_DIRS.items():
        entries = _papers().get(section, [])
        lines = [
            BANNER,
            "",
            f"# Source Papers: {SECTION_TITLES.get(section, section.title())}",
            "",
        ]
        lines.extend(markdown_citation(entry) for entry in entries)
        path = PROJECT_ROOT / "tutorials" / directory / "papers.md"
        path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
        written.append(path)
    return written


def main() -> int:
    index = write_index()
    sections = write_section_markdown()
    tutorials = write_tutorial_markdown()
    total = sum(len(entries) for entries in _papers().values())
    print(f"{total} papers across {len(SECTIONS)} sections")
    for path in [index, *sections, *tutorials]:
        print(f"  wrote {path.relative_to(PROJECT_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
